[package]
name = "lcpc-brakedown-pc"
version = "0.1.1"
authors = ["kwantam <kwantam@gmail.com>"]
edition = "2018"
description = "polynomial commitment scheme from SDIG expander code"
license = "Apache-2.0"
repository = "https://github.com/conroi/lcpc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = "0.12"
#ff = {git = "https://github.com/iammadab/ff", branch = "main"}
itertools = "0.10"
lcpc-2d = { path = "../lcpc-2d", version = "0.1.1" }
ndarray = ">=0.11.0,<0.15"
num-traits = "0.2"
rand = "0.8"
rand_chacha = "0.3"
rayon = "1.5"
sprs = "0.10"
typenum = "1.13"

[dev-dependencies]
bincode = "1.3"
blake3 = { version = "=1.0", features = ["traits-preview"] }
merlin = "2.0"
paste = "1.0"
lcpc-test-fields = { path = "../lcpc-test-fields", version = "0.1.1" }
goldilocks = { git = "https://github.com/iammadab/Goldilocks", branch = "ff-0.12" }

[features]
bench = []
